export const typeColors: Record<string, string> = {
  fire: 'bg-primary text-on-primary',
  flying: 'bg-secondary text-on-secondary',
  grass: 'bg-[#2e7d32] text-white',
  poison: 'bg-[#7b1fa2] text-white',
  water: 'bg-secondary text-on-secondary',
  electric: 'bg-tertiary-container text-on-tertiary-container',
  psychic: 'bg-tertiary text-on-tertiary',
  normal: 'bg-outline text-surface-container-lowest',
  ghost: 'bg-[#7b1fa2] text-white',
  bug: 'bg-[#827717] text-white',
  ground: 'bg-[#8d6e63] text-white',
  rock: 'bg-[#5d4037] text-white',
  fighting: 'bg-[#b71c1c] text-white',
  ice: 'bg-[#00acc1] text-white',
  dragon: 'bg-[#3949ab] text-white',
  dark: 'bg-[#212121] text-white',
  steel: 'bg-[#546e7a] text-white',
  fairy: 'bg-[#c2185b] text-white',
};
